language: node_js
node_js:
  - '8'
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - npm run build:github
deploy:
  provider: pages
  local_dir: dist
  repo: stbui/angular-material-app
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
  target_branch: gh-pages
cache:
  directories:
    - node_modules
